### ISSUE TITLE
"jefflessard/plex-vaapi-amdgpu-mod" could not be found on registry-1.docker.io

### ISSUE THREAD

**Issue by sammcj** [jefflessard/plex-vaapi-amdgpu-mod#3]
I don't seem to be able to get this mod to install - for some reason when the container starts it can't find the image on docker's registry - however I can pull it when running docker pull jefflessard/plex-vaapi-amdgpu-mod normally?

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding "jefflessard/plex-vaapi-amdgpu-mod" to container
[mod-init] "jefflessard/plex-vaapi-amdgpu-mod" could not be found on registry-1.docker.io
```

**Comment by sammcj** [comment]
@jefflessard any idea why this might be happening with your mod?

**Comment by nphalem** [comment]
Don't have this issue, can you check again?

**Comment by sammcj** [comment]
Oh wow blast from the past! 😅 

Added the mod to my plex container again, looks like the error is slightly different but it's still a problem:

```
docker logs plex
[mod-init] Running Docker Modification Logic
[mod-init] Adding "jefflessard/plex-vaapi-amdgpu-mod" to container
[mod-init] "jefflessard/plex-vaapi-amdgpu-mod" digest could not be fetched from registry-1.docker.io, checking local cache
[mod-init] (ERROR) OFFLINE: "jefflessard/plex-vaapi-amdgpu-mod" not found in modcache, skipping
[migrations] started
```

```yaml
services:
  &name plex:
...
    image: lscr.io/linuxserver/plex:latest
....
    environment:
      - DOCKER_MODS="jefflessard/plex-vaapi-amdgpu-mod"
...

  &name modmanager:
    <<: [*autoupdate, *restart, *secopts]
    image: lscr.io/linuxserver/modmanager:latest
    container_name: *name
    hostname: *name
    environment:
      DOCKER_MODS: "linuxserver/mods:universal-package-install|linuxserver/calibre-web:calibre|jefflessard/plex-vaapi-amdgpu-mod|linuxserver/mods:jellyfin-amd"
      DOCKER_HOST: "tcp://dockerproxy:2375"
    volumes:
      - /opt/docker-data/lscr/modcache:/modcache
    depends_on:
      - dockerproxy
    networks:
      docker-proxynet:
    labels:
      traefik.enable: false
      org.hotio.pullio.update: true
```
